# Ref: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

name: Build and publish Docker image

on:
  # TOFIX:
  #   release:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  #     types:
  #       - published

  workflow_dispatch:
    # This GH Action will be manually trigger
    inputs:
      branch:
        description: "Git branch"
        required: true
        default: main
      registry:
        description: "Docker registry"
        required: true
        default: ghcr.io
      image_name1:
        description: "Docker image name1"
        required: true
        default: gatewaydw/workflow-host-dbt-docs
      tag:
        description: "Docker image tag"
        required: true
        default: latest

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Log in to Docker Registry - ${{ github.event.inputs.registry }}
        uses: docker/login-action@v2
        with:
          registry: ${{ github.event.inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ${{ github.event.inputs.registry }}/${{ github.event.inputs.image_name }}:${{ github.event.inputs.tag }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image 1 - ${{ github.event.inputs.registry }}/${{ github.event.inputs.image_name1 }}:${{ github.event.inputs.tag }} , latest
        uses: docker/build-push-action@v3
        # If you encounter `unexpected status: 403 Forbidden` when pushing image to the registry,
        # Check if the repo have the write access to the package
        # https://github.com/docker/build-push-action/issues/687#issuecomment-1238980158
        # Use multiple tags - https://stackoverflow.com/a/70869609
        with:
          context: ./devops
          file: ./devops/Dockerfile
          # build-args: |
          #   PIPENVFILE=mage-el-requirements.txt
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.event.inputs.registry }}/${{ github.event.inputs.image_name1 }}:${{ github.event.inputs.tag }} , ${{ github.event.inputs.registry }}/${{ github.event.inputs.image_name1 }}:latest
          # labels: ${{ steps.meta.outputs.labels }}
          labels: |
            description="Docker Image for dbt docs hosting"
