name: Build and Deploy dbt docs to Github Pages

on:
  # No access to secrets
  # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request:
    branches: [main]

  push:
    branches:
      - main
  # workflow_dispatch:
  
jobs:
  call-workflow:
    uses: GatewayDW/workflow-host-dbt-docs/.github/workflows/host_dbt_docs.yml@main
    with:
      runner_type: self-hosted
      dbt_project_name: DOR_Migration
      dbt_project_path: etl/DOR

    # https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
    secrets:
      secrets_dbt_profile: ${{ secrets.DBT_PROFILE }}
