name: Host dbt doc on website

on:
  workflow_call:
    inputs:
      # config-path:
      #   required: true
      #   type: string
      env:
        required: true
        type: string

      dbt_project_path:
        required: true
        type: string

    # secrets:
    #   token:
    #     required: true
permissions:
  contents: write
  
jobs:
  # triage:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/labeler@v4
  #     with:
  #       repo-token: ${{ secrets.token }}
  #       configuration-path: ${{ inputs.config-path }}

  build:  
    runs-on: ${{ inputs.env }} # self-hosted # environment to be used
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
        
      - name: Install dbt
        run: pip install dbt-sqlserver==1.3.0
        
      - name: Install dbt deps
        run: dbt deps
        working-directory: ${{ inputs.dbt_project_path }}

      - name: (Windows) create dbt model (.sql) to document current CI build no.
        if: runner.os == 'Windows'
        run: |
          mkdir ${{ inputs.dbt_project_path }}/models/cicd -Force
          $content = echo "select 
              '${{ github.run_number }}' as build_no,
              '${{ github.repositoryUrl }}' as repo_url,
              '${{ runner.name }}' as runner_name,
              '${{ runner.os }}' as runner_os
          "
          Out-File -FilePath ${{ inputs.dbt_project_path }}/models/cicd/dbt_build.sql -InputObject $content -Encoding utf8

      - name: dbt run dbt_build
        if: runner.os == 'Windows'
        run: dbt run --select dbt_build --profiles-dir .
        working-directory: ${{ inputs.dbt_project_path }}  

      - name: dbt docs gen
        run: dbt docs generate --profiles-dir .
        working-directory: ${{ inputs.dbt_project_path }}

      - name: dbt compile
        run: dbt compile --profiles-dir .
        working-directory: ${{ inputs.dbt_project_path }}
        
      - name: Upload Artifacts 🔺 # The project is then uploaded as an artifact named 'site'.
        uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ${{ inputs.dbt_project_path }}/target # etl/CDW_FB_SQ
      

  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts 🔻 # The built project is downloaded into the 'site' folder.
        uses: actions/download-artifact@v1
        with:
          name: artifact

      # - name: ls 
      #   run: |
      #     ls -R
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: artifact # etl/CDW_FB_SQ/target
